import type { Experience } from "./types";

export const experiences: Experience[] = [
  {
    id: "miton",
    company: "Miton",
    role: "AI Engineer & Product Owner",
    start: "2025-10",
    end: "present",
    dateDisplay: "Oct 2025 - Present",
    location: "Prague, Czechia",
    modality: "Hybrid",
    logo: "/images/experience/miton.jpeg",
    link: "https://miton.cz",
    description: [
      "Built an AI-powered data intelligence platform from scratch as sole engineer.",
      "Embedding-based semantic search over 150K+ records: pgvector HNSW indexing, JSONB prefilters across 20+ dimensions, quality-based reranking, sub-second query latency.",
      "Multi-source data pipelines ingesting from 5+ external APIs, with automated enrichment and deduplication.",
      "Identity resolution system matching profiles across sources using deterministic and LLM-scored fuzzy linking.",
      "GPT-powered extraction pipelines: structured keyword profiles, intent parsing, profile summarization.",
      "Full backend (FastAPI, PostgreSQL, SQLAlchemy, Alembic) and frontend (Next.js), plus auth, admin tools, and MCP server.",
      "Multi-environment infrastructure (local/dev/prod) on Hetzner with nginx, automated deployment, and DB sync tooling.",
      "Technical due diligence and AI strategy advisory for the fund's portfolio.",
    ],
    skills: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "pgvector",
      "FastMCP",
      "OpenAI",
      "SQLAlchemy",
      "Alembic",
      "Next.js",
      "TypeScript",
      "Docker",
      "nginx",
      "Claude Code",
      "Codex",
    ],
  },
  {
    id: "stealth-startup",
    company: "Stealth Startup (Robotics & AI)",
    role: "Founder & CEO",
    start: "2025-05",
    end: "2026-01",
    dateDisplay: "May 2025 - Jan 2026",
    location: "Munich, Bavaria, Germany",
    logo: "/images/experience/stealth-startup.jpeg",
    description: [
      "Founded a robotics & AI startup building automated shelf-restocking for supermarkets.",
      "Trained object detection and instance segmentation models (YOLOv11) achieving 94.5% mAP50 on shelf product recognition from a small initial dataset.",
      "Built a scalable dataset pipeline: DVC versioning, session-based metadata architecture with contributor/device tracking, multi-format export (COCO/YOLO), designed for international rollout.",
      "Built the grasping point detection pipeline using VLMs for robotic pick-and-place.",
      "Led investor communication and pitching. Secured LOIs and entered deal negotiations with REWE Digital.",
      "Managed team, product strategy, and company operations.",
    ],
    skills: [
      "Python",
      "PyTorch",
      "YOLOv11",
      "OpenCV",
      "VLMs",
      "DVC",
      "COCO",
      "CVAT",
    ],
  },
  {
    id: "fzi",
    company: "FZI Research Center for Information Technology",
    role: "GenAI & CV Researcher",
    start: "2025-03",
    end: "2025-09",
    dateDisplay: "Mar 2025 - Sep 2025",
    location: "Karlsruhe, Germany",
    modality: "Remote",
    logo: "/images/experience/fzi.jpeg",
    link: "https://www.fzi.de/en/",
    description: [
      "Enhanced a multi-modal pipeline to extract semantics from schematics, benchmarking it against state-of-the-art Vision Language Models (VLMs).",
      "Independently created a comprehensive dataset of Raspberry Pi schematics for computer vision analysis.",
      "Increased object detection (Faster R-CNN) performance by 7.3% mAP.",
    ],
    skills: ["VLM", "Multi-Modal Deep Learning", "Python", "PyTorch", "Object Detection"],
  },
  {
    id: "synthavo",
    company: "synthavo",
    role: "Agentic AI Engineer",
    start: "2024-12",
    end: "2025-07",
    dateDisplay: "Dec 2024 - Jul 2025",
    location: "Stuttgart, Germany",
    modality: "Hybrid",
    logo: "/images/experience/synthavo.jpeg",
    link: "https://www.synthavo.de/en/",
    description: [
      "Independently built an agentic AI system for industrial spare part recognition from initial concept.",
      "Built a multimodal LLM agent that reduced spare part identification from hours of manual lookup to seconds via conversational AI.",
      "Designed the full architecture: LangChain + LangGraph agent orchestration, ChromaDB vector store, RAG retrieval pipeline.",
      "Delivered a working prototype that the company then hired an external team to scale into production.",
      "Presented technical strategy and solutions to both technical and business stakeholders.",
    ],
    skills: ["Python", "LangChain", "LangGraph", "ChromaDB", "RAG", "Groq API"],
  },
  {
    id: "ciirc-researcher",
    company: "Czech Institute of Informatics, Robotics and Cybernetics",
    role: "Machine Learning Researcher",
    start: "2023-03",
    end: "2023-07",
    dateDisplay: "Mar 2023 - Jul 2023",
    location: "Prague, Czechia",
    modality: "Part-time",
    logo: "/images/experience/cvut-ciirc.jpeg",
    link: "https://www.ciirc.cvut.cz/",
    description: [
      "Research on identifying the most congested areas in urban environments (Dublin, Luxembourg).",
      "Adapted gravitational clustering techniques to detect high-traffic regions.",
      "Contributed to centralized traffic routing in SUMO simulation.",
      "Co-authored a paper submitted to Expert Systems with Applications (ESWA), Elsevier.",
    ],
    skills: ["Machine Learning", "Python", "SUMO", "Traffic Simulation", "Clustering"],
  },
  {
    id: "charles",
    company: "Charles University in Prague",
    role: "Data Analyst",
    start: "2020-07",
    end: "2022-12",
    dateDisplay: "Jul 2020 - Dec 2022",
    location: "Prague, Czechia",
    modality: "Contract",
    logo: "/images/experience/charles-uni.png",
    link: "https://cuni.cz/UKEN-1.html",
    description: [
      "Project 1 (2020): Analyzed 600K+ records on internal migration flows in the Czech Republic (MySQL, Python).",
      "Project 2 (2022): Animated choropleth map of allowance-for-living distribution (Python, GeoJSON, NumPy, Pandas, Plotly).",
    ],
    skills: ["Python", "MySQL", "Pandas", "Plotly", "Data Visualization"],
  },
  {
    id: "us-afrl",
    company: "US Air Force Research Lab & CTU FEE AI Center",
    role: "Artificial Intelligence Researcher",
    start: "2021-09",
    end: "2022-07",
    dateDisplay: "Sep 2021 - Jul 2022",
    location: "Prague, Czechia",
    modality: "Part-time",
    logo: "/images/experience/ai-fee-ctu.png",
    link: "https://www.aic.fel.cvut.cz/",
    description: [
      "Contributed to FRAS (Flexible and Resilient Autonomous Systems) research project funded by US Air Force.",
      "Developed Python/PDDL environment generator for single and multi-agent AI planning strategies.",
      "Applied classical planning and game theory for adversarial environments.",
    ],
    skills: ["Classical Planning", "Game Theory", "PDDL", "Python"],
  },
  {
    id: "scilif",
    company: "SCILIF",
    role: "Android App Developer",
    start: "2021-07",
    end: "2021-10",
    dateDisplay: "Jul 2021 - Oct 2021",
    location: "Prague, Czechia",
    modality: "Contract",
    logo: "/images/experience/sunfibre-logo.jpeg",
    link: "https://www.scilif.com/",
    description: [
      "Designed and built an Android app to manage multiple Bluetooth Low Energy devices (Kotlin).",
    ],
    skills: ["Android", "Kotlin", "BLE"],
  },
  {
    id: "cbf",
    company: "Czech Basketball Federation",
    role: "Basketball Referee",
    start: "2016-09",
    end: "2020-06",
    dateDisplay: "Sep 2016 - Jun 2020",
    location: "Prague, Czechia",
    modality: "Part-time",
    logo: "/images/experience/cbf-logo.png",
    link: "https://cbf.cz.basketball/o-cbf/p81",
    description: [
      "Officiated 100+ games across U14, U16, U18, and adult categories.",
      "Developed leadership, teamwork, and decision-making under pressure.",
    ],
    skills: ["Leadership", "Decision-making"],
  },
  {
    id: "ciirc-intern",
    company: "Czech Institute of Informatics, Robotics and Cybernetics",
    role: "Robotics Intern",
    start: "2017-04",
    end: "2019-08",
    dateDisplay: "Apr 2017 - Aug 2019",
    location: "Prague, Czechia",
    logo: "/images/experience/cvut-ciirc.jpeg",
    link: "https://www.ciirc.cvut.cz/",
    description: [
      "Automated 3D printing tasks for ABB YUMI robot at CIIRC.",
      "Developed a scannable coding system to sort printed parts.",
    ],
    skills: ["Robotics", "ABB YUMI"],
  },
  {
    id: "launchx",
    company: "LaunchX Entrepreneurship Program",
    role: "Founder & Winner, MIT Startup Competition",
    start: "2018-09",
    end: "2019-06",
    dateDisplay: "Sep 2018 - Jun 2019",
    location: "Brussels, Belgium",
    logo: "/images/experience/mit-launchx.jpeg",
    description: [
      "Developed a startup connecting visually impaired people with visually healthy people.",
      "Won Brussels Demo Day; invited to MIT (Boston, USA) for further development.",
    ],
    skills: ["Entrepreneurship", "Product"],
  },
];
